apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #{Octopus.Project.Name}
    version: #{Octopus.Release.Number}
  name: #{Octopus.Project.Name}
  namespace: #{Project.Pitstop.Namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Octopus.Project.Name}
      version: #{Octopus.Release.Number}
  template:
    metadata:
      labels:
        app: #{Octopus.Project.Name}
        version: #{Octopus.Release.Number}
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: #{Project.Pitstop.Image}
        imagePullPolicy: IfNotPresent
        name: #{Octopus.Project.Name}
      restartPolicy: Always

