apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #{Octopus.Project.Name}
    version: "2.0"
  name: #{Octopus.Project.Name}
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Octopus.Project.Name}
      version: #{Octopus.Release.Number}
  template:
    metadata:
      labels:
        app: #{Octopus.Project.Name}
        version: #{Octopus.Release.Number}
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: #{Project.Pitstop.Image}
        imagePullPolicy: IfNotPresent
        name: #{Octopus.Project.Name}
        ports:
        - containerPort: 5100
      restartPolicy: Always
