apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #{Octopus.Project.Name}
  name: #{Octopus.Project.Name}
  namespace: #{Project.Pitstop.Namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Octopus.Project.Name}
  template:
    metadata:
      labels:
        app: #{Octopus.Project.Name}

    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: #{Project.Pitstop.Image}
        imagePullPolicy: IfNotPresent
        name: #{Octopus.Project.Name}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: #{Octopus.Project.Name}
  name: #{Octopus.Project.Name}
  namespace: #{Project.Pitstop.Namespace}
spec:
  type: ClusterIP
  ports:
  - name: "customermanagementapi"
    port: 5100
    targetPort: 5100
  selector:
    app: #{Octopus.Project.Name}
