apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #{Octopus.Project.Name}
    version: #{Octopus.Release.Number}
  name: #{Octopus.Project.Name}
  namespace: #{Project.Pitstop.Namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Octopus.Project.Name}
      version: #{Octopus.Release.Number}
  template:
    metadata:
      labels:
        app: #{Octopus.Project.Name}
        version: #{Octopus.Release.Number}
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: #{Project.Pitstop.Image}
        imagePullPolicy: IfNotPresent
        name: #{Octopus.Project.Name}
        ports:
        - containerPort: 7005
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: #{Octopus.Project.Name}
  name: #{Octopus.Project.Name}
  namespace: #{Project.Pitstop.Namespace}
spec:
  type: LoadBalancer
  ports:
  - name: "7005"
    port: 7005
    targetPort: 7005
  selector:
    app: #{Octopus.Project.Name}
    version: #{Octopus.Release.Number}

