apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: auditlogservice
    version: "1.0"
  name: auditlogservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: auditlogservice
      version: "1.0"
  template:
    metadata:
      labels:
        system: pitstop
        app: auditlogservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/auditlogservice:1.0
        imagePullPolicy: IfNotPresent
        name: auditlogservice
      restartPolicy: Always

