apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: notificationservice
    version: v1
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: notificationservice
        version: v1
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: pitstop/notificationservice:latest
        imagePullPolicy: IfNotPresent
        name: notificationservice
      restartPolicy: Always
