apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: repairmanagementapi
    version: "1.0"
  name: repairmanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repairmanagementapi
      version: "1.0"
  template:
    metadata:
      labels:
        app: repairmanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: ghcr.io/hanaim-devops/pitstop-team-luna/repairmanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: repairmanagementapi
        ports:
        - containerPort: 5300
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: repairmanagementapi
  name: repairmanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "http-5300"
    port: 5300
    targetPort: 5300
    nodePort: 30013
  selector:
    app: repairmanagementapi

