apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: workshopmanagementeventhandler
    version: v1
  name: workshopmanagementeventhandler
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: workshopmanagementeventhandler
        version: v1
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: pitstop/workshopmanagementeventhandler:latest
        imagePullPolicy: IfNotPresent
        name: workshopmanagementeventhandler
      restartPolicy: Always
