apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notificationservice-scaledobject
  namespace: pitstop
spec:
  scaleTargetRef:
    name: notificationservice
  pollingInterval: 5
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: Notifications
        queueLength: "5"
        host:  amqp://rabbitmquser:DEBmbwkSrzy9D1T9cJfa@rabbitmq.pitstop.svc.cluster.local:5672
  fallback: 
    failureThreshold: 2                                    
    replicas: 2  
    