apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: pitstop
spec:
  secretTargetRef:
    - parameter: username
      name: rabbitmq-secret
      key: username
    - parameter: password
      name: rabbitmq-secret
      key: password