apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: a2lhbGktYWRtaW4=
  passphrase: a2lhbGktYWRtaW4tcGFzc3dvcmQ=

---

# kiali-admin
# kiali-admin-password