name: Docker Image CI

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/CustomerManagementAPI
    steps:
       - uses: actions/checkout@v3
       - name: Docker Hub Login
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build Docker Image
         run:  | 
           docker build . --file ./src/pitstop-dotnet-aspnet-base --tag pitstop-dotnet-aspnet-base:1.0
           docker build . --file Dockerfile --tag customermanagementapi:$(date +%s)
       

          
         
