name: Docker Image CI

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/CustomerManagementAPI
    steps:
       - uses: actions/checkout@v3
       - name: Build the Docker image
         run: docker build . --file Dockerfile --tag customermanagementAPI:$(date +%s)
