name: Docker Application Services CI

on:
  workflow_dispatch

env:
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE }}
  
  
jobs:

 create-version-number:
   runs-on: ubuntu-latest
   steps:
       - id: version
         run: echo "version=$(date +'%Y.%m')" >> "$GITHUB_OUTPUT"
   outputs:
     version: ${{ steps.version.outputs.version }}
         
 create-feature-branch:
    needs: [create-version-number]
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
        echo "${{needs.create-version-number.outputs.version}}"
    - name: Create Feature Tenant
      uses: OctopusDeploy/run-runbook-action@v3.0.3
      with:
        project: Administration
        runbook: Create Feature Branch Tenant
        environments: sync
        variables: Pitstop.Orhestration.Feature.Branch:${{ steps.extract_branch.outputs.branch }}

 call-docker-build-push-as:
    needs: [create-version-number]
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: AuditlogService
      docker-image-name: pitstop-audit-log-service
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit

 call-docker-build-push-cm:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: CustomerManagementAPI
      docker-image-name: pitstop-customer-management-
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-push-is:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: InvoiceService
      docker-image-name: pitstop-invoice-service
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-push-ns:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: NotificationService
      docker-image-name: pitstop-notification-service
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-push-ts:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: TimeService
      docker-image-name: pitstop-time-service
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-push-vm-api:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: VehicleManagementAPI
      docker-image-name: pitstop-vehicle-management-api
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-push-web-app:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: WebApp
      docker-image-name: pitstop-web-app
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-wm-api:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: WorkshopManagementAPI
      docker-image-name: pitstop-workshop-management-api
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
 call-docker-build-wm-eh:
    uses: adamoctoclose/pitstop/.github/workflows/reusable-docker.yml@main
    with:
      service-name: WorkshopManagementEventHandler
      docker-image-name: pitstop-workshop-management-event-handler
      docker-image-version: ${{needs.create-version-number.outputs.version}}
    secrets: inherit
      
    
  
