name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test
    env:
      Headless: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/pitstop.sln

    - name: Build
      run: dotnet build --no-restore ./src/pitstop.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/pitstop.sln

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run shell script
      run: ./RebuildAllDockerImages.sh
      working-directory: src
      shell: bash

    # TODO: Actually publish the Docker images to a container registry
  push-docker-images:
    needs: publish
    runs-on: ubuntu-latest
    name: push docker images

    steps:
    # Checkout the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.PAT_GITHUB }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Run the push-images.ps1 script
    - name: Execute push images script
      run: ./push-images.ps1
    
