name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test
    env:
      Headless: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/pitstop.sln

    - name: Build
      run: dotnet build --no-restore ./src/pitstop.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/pitstop.sln

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

        # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.PAT_GITHUB }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Run shell script
      run: ./RebuildAllDockerImages.ps1
      working-directory: src
      shell: pwsh

    # Run the push-images.ps1 script
    - name: Execute push images script
      run: ./push-images.ps1
      working-directory: src
      shell: pwsh

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    name: deploy
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Minikube
    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube driver: docker

    - name: Configure KUBECONFIG
      run: |
        mkdir -p $HOME/.kube
        cp src/groep5.yaml $HOME/.kube/config  # Update path if needed
      env:
        KUBECONFIG: $HOME/.kube/config

    # Set the Kubernetes context
    - name: Use Kubernetes Context
      run: kubectl config use-context groep5

    # Stop existing pods (uses stop-all.ps1 script)
    - name: Stop Pods
      run: ./stop-all.ps1
      working-directory: src/k8s/scripts
      shell: pwsh

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.PAT_GITHUB }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Start pods (uses start-all.ps1 script)
    - name: Start Pods
      run: ./start-all.ps1 -nomesh
      working-directory: src/k8s/scripts
      shell: pwsh
