name: Reusable Docker


on:
  workflow_call:
    inputs:
      service-name:  
        required: true
        type: string
      docker-image-name:
        required: true
        type: string
      docker-image-version:
        required: true
        type: string
      feature-branch-name:
        required: false
        type: string
env:
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       
       - uses: actions/checkout@v3
       
       - name: Docker Hub Login
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build Docker Image
         working-directory: src/${{ inputs.service-name }}
         run:  | 
           docker build --tag adamoctoclose/${{ inputs.docker-image-name }}:${{ inputs.docker-image-version }} .
           docker push adamoctoclose/${{ inputs.docker-image-name }}:${{ inputs.docker-image-version }}

       - name: Create Octopus Release
         uses: OctopusDeploy/create-release-action@v3
         with: 
            project: ${{ inputs.docker-image-name }}
            release_number: ${{ inputs.docker-image-version }}-${{ inputs.feature-branch-name }}
            channel: Development

       - name: Deploy Octopus Release
         uses: OctopusDeploy/deploy-release-action@v3.0.4
         with: 
             project: ${{ inputs.docker-image-name }}
             release_number: ${{ inputs.docker-image-version }}-${{ inputs.feature-branch-name }}
             environments: Development
             variables: Project.Pitstop.Branch:${{ inputs.feature-branch-name }}
            
