name: Reusable Docker


on:
  workflow_call:
    inputs:
      service-name:  
        required: true
        type: string
      docker-image-name:
        required: true
        type: string  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       
       - uses: actions/checkout@v3
       
       - name: Docker Hub Login
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Create Version Number
         id: version
         run: echo "version=$(date +'%Y.%m')" >> $GITHUB_OUTPUT

       - name: Build Docker Image
         working-directory: ${{ inputs.service-name }}
         run:  | 
           docker build --tag adamoctoclose/${{ inputs.docker-image-name }}:${{ steps.version.outputs.version }}.${{ github.run_number }} .
           docker push adamoctoclose/${{ inputs.docker-image-name }}:${{ steps.version.outputs.version }}.${{ github.run_number }}
