name: Reusable Docker


on:
  workflow_call:
    inputs:
      service-name:  
        required: true
        type: string
      docker-image-name:
        required: true
        type: string
      docker-image-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       
       - uses: actions/checkout@v3
       
       - name: Docker Hub Login
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build Docker Image
         working-directory: src/${{ inputs.service-name }}
         run:  | 
           docker build --tag adamoctoclose/${{ inputs.docker-image-name }}:${{ inputs.docker-image-version }} .
           docker push adamoctoclose/${{ inputs.docker-image-name }}:${{ inputs.docker-image-version }}
